source:        _src
destination:   _site
plugins:       _src/_plugins

markdown:      redcarpet2
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

pygments:      true
permalink:     /blog/:year/:month/:day/:title/


# Plugins
category_dir:  blog/categories/

# custom Variables
name: Lawn of laerador
description: "(:"
author: laerador
domain: "http://lc3dyr.de"
url: "http://lc3dyr.de"
refresh: 0
