source:        _src
destination:   _site
plugins:       _src/_plugins

markdown:      redcarpet

pygments:      true
permalink:     /blog/:year/:month/:day/:title/


# Plugins
category_dir:  blog/categories/

# custom Variables
name: Lawn of laerador
description: "(:"
domain: "http://lc3dyr.de"
url: "http://lc3dyr.de"
refresh: 0
